### ISSUE TITLE
Homebridge crashing

### ISSUE THREAD

**Issue by Al-Mclean** [iRayanKhan/homebridge-tuya#117]
**Checklist**
- [Y] I have read the common issues wiki page
- [Y] I have checked to make sure the plugin is up to date

**Describe the bug**
I am experiencing homebridge crashing after setting the the Tuya plug-in and adding a device. The device (a Kogan kettle) works fine but after about 12 hours of running Homebridge will crash (output listed below)

**To Reproduce**
Run homebridge with a device in the config

**Screenshots**

```
[TuyaDiscovery] UDP from 192.168.1.6:6667 0x000055aa...0x0000aa55
[7/22/2020, 10:05:42 PM] [TuyaPlatform] Discovered Kogan Kettle (41341132bcddc2675565) identified as outlet (3.3)
[TuyaAccessory] Changing ping gap for Kogan Kettle to 9s
.
[7/22/2020, 10:05:43 PM] [TuyaPlatform] Connected to Kogan Kettle
[TuyaAccessory] Sending first query to Kogan Kettle (3.3)
[7/22/2020, 10:05:46 PM] [TuyaPlatform] Discovered a device that has not been configured yet (bf6cef3ff7d77f73f6nlat@192.168.1.4).
.
[TuyaDiscovery] UDP from 192.168.1.4:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.1.4:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.1.4:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.1.4:6667 0x000055aa...0x0000aa55
.
.
.
.
[TuyaAccessory] Socket had a problem and will reconnect to Kogan Kettle (Error: ERR_CONNECTION_TIMED_OUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Kogan Kettle (Error: ERR_CONNECTION_TIMED_OUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.

<--- Last few GCs --->

[5816:0x2ec5188] 30067190 ms: Mark-sweep 228.6 (231.7) -> 228.1 (231.7) MB, 1679.4 / 5.7 ms  (average mu = 0.306, current mu = 0.307) allocation failure scavenge might not succeed
[5816:0x2ec5188] 30069599 ms: Mark-sweep 228.6 (231.7) -> 228.2 (231.7) MB, 1567.4 / 5.7 ms  (average mu = 0.328, current mu = 0.350) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x29b4e851 <JSObject>
    0: builtin exit frame: toString(this=0x5ce87f29 <Error map = 0x2f0485ad>,0x5ce87f29 <Error map = 0x2f0485ad>)

    1: StubFrame [pc: 0xe24880]
    2: StubFrame [pc: 0xed739c]
    3: /* anonymous */ [0x5ea93151] [/usr/local/lib/node_modules/homebridge-tuya/lib/TuyaAccessory.js:~132] [pc=0x418b1fc0](this=0x5ea92c45 <Socket map = 0x3c73c745>,0x5ce87f29 <Error map = 0x2f0485ad>)
    4: _onTimeout [0...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
Aborted
```

**Environment (please complete the following information):**
 - OS: 
-  iOS version:
-  Homehubs: 
 - Node Version: 
 - Plugin Version:
-  Accessory Type: Kogan Kettle

**Additional context**
I really appreciate the effort the community has put into this and homebridge in general - hopefully someone can assist me here (and apologies if there has been a solution posted which I haven't spotted)

**Comment by Al-Mclean** [comment]
Further  information:

I believe part of my problem is that Tuya discovery is contiunally finding my RoboRock vacuum and reporting it as an un-configured device, which I believe is leading to further issues and the eventual crash. As I understand it, the RoboRock dosen't use a Tuya type Protocol.

Is there a way to inhibit or disable discovery - either for that device, IP or in general?

Thanks

**Comment by galzil** [comment]
I have the same issue, I have to restart about once a day.
Is this connected with this [issue](https://github.com/iRayanKhan/homebridge-tuya/issues/78)?

**Comment by Al-Mclean** [comment]
That's my suspicion - that its some kind of overflow issue (too many sockets maybe). Unfortunately I don't have the Node JS experience to do much more testing

**Comment by Al-Mclean** [comment]
After a crash course in Node JS (and some help from one of my Dev's) I coded up a solution to switch off the TuyaDiscovery module after 10 "UDP from" messages. This improved the stability but still crashed after a couple of days after many: 

[TuyaAccessory] Socket had a problem and will reconnect to Kogan Kettle (ENFILE)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.

Looks like a bit more work to do.

**Comment by ngori** [comment]
@Al-Mclean is it possible to share your solution via a fork?  I just switched from the web plugin to the LAN plugin due to some instability with the web plugin but am now bumping into the same issue here with my 1 Tuya device.

**Comment by ngori** [comment]
Nevermind.  I just commented out the one console.log in TuyaDiscovery.js that I kept seeing. Good enough until resolved by the next version

**Comment by Al-Mclean** [comment]
No Problems @ngori, I've achieved some stability improvements but an still having the crashing issue - it just takes longer now. Once I have a more robust solution I will fork and share.

**Comment by drheck** [comment]
Hello,
i have also a problem with crashing&restaring after 2 or 3 hours.

Sep 21 10:58:40 hbridge3 homebridge[13482]: (node:13482) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
Sep 21 11:10:16 hbridge3 homebridge[13482]: [2020-9-21 11:10:16] [ZWayServer] ERROR: Request failed! Error code EMFILE. Check the URL in config.json and ensure that the URL can be reached from this system!

Is there a solution?
Thanks
Peter

**Comment by Al-Mclean** [comment]
try changing 

`if (err && (err.code === 'ECONNRESET' || err.code === 'EPIPE') && this._connectionAttempts < 10) {`

to:

`if (err && (err.code === 'ECONNRESET' || err.code === 'EPIPE' || err.code === 'EHOSTUNREACH') && this._connectionAttempts < 10) {`

That worked for me

**Comment by sjors98** [comment]
Hi! Can anyone make a PR for this? I experience the same issue...

**Comment by AndrewJ1990** [comment]
Just adding that I'm having the same problem with a couple of devices causing this. Restarting homebridge fixes the problem, but it's happening multiple times a day

```
[TuyaAccessory] Socket had a problem and will reconnect to Master Blind 2 (Error: ERR_CONNECTION_TIMED_OUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
```

**Comment by ElphaX** [comment]
Allegedly restarting homebridge has fixed the issue for several users. Closing issue until further notice
