### ISSUE TITLE
Unable to control discovered device.

### ISSUE THREAD

**Issue by travisgerard** [iRayanKhan/homebridge-tuya#206]
I'm trying to get a dimmable rgbw light bulb working. It shows up in the home app and can be controlled but doesn't actually do anything. Does anyone have any insight to this?

```
[2/21/2021, 14:35:57] [TuyaLan] Discovered Jason Lamp (erau) identified as RGBTWLight (3.3)
[TuyaAccessory] Changing ping gap for Jason Lamp to 9s
[TuyaAccessory DEBUG] reconnect called for Jason Lamp
[TuyaAccessory] Discovery ended.
[2/21/2021, 14:35:58] [TuyaLan] Connected to Jason Lamp
[TuyaAccessory] Sending first query to Jason Lamp (3.3)
[TuyaAccessory] Heard back from Jason Lamp with command 10
[2/21/2021, 14:35:58] [TuyaLan] Ready to handle Jason Lamp (RGBTWLight:3.3) with signature {"20":false,"21":"white","22":1000,"23":21,"24":"00fb003200be","25":"030e0d0000e80383031c00000000","26":0}
[TuyaAccessory] Color format for Jason Lamp (3.3) is undetectable.

```

Turning the bulb on and off in the home app gives only these two entries (other devices using this plugin always have a "heard back" response after the command):

```
[TuyaAccessory] Sending Jason Lamp {"1":true}
[TuyaAccessory] Sending Jason Lamp {"1":false}
```

**Comment by tehfalcon-vw** [comment]
I'm having the same issue, and home bridge is throwing these errors:

[3/1/2021, 5:33:30 AM] [homebridge-tuya] This plugin generated a warning from the characteristic 'Color Temperature': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info.
[3/1/2021, 5:33:30 AM] [homebridge-tuya] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[3/1/2021, 5:33:30 AM] [homebridge-tuya] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[3/1/2021, 5:33:30 AM] [homebridge-tuya] This plugin generated a warning from the characteristic 'Off': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.

**Comment by MrGigiTheBunny** [comment]
Same thing happening to me, it shows up in the Home app but doesn't actually do anything.

HomeBridge Logs:
`[3/14/2021, 7:38:53 PM] [homebridge-tuya] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.`
^ only error that I get

I also get these
`[Tuya] Sending Gigi lamp {"1":true}
[Tuya] Sending Gigi lamp {"1":false}`

**Comment by sj-pr** [comment]
Was anyone able to fix this issue? Something happening to me for a White and RGB bulb...
[3/20/2021, 21:54:38] [homebridge-tuya] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.

**Comment by tehfalcon-vw** [comment]
> Was anyone able to fix this issue? Something happening to me for a White and RGB bulb...
> `[3/20/2021, 21:54:38] [homebridge-tuya] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.`

Yes I fixed it, you need to define the characteristic's (parameters) of the bulb in the config. I used the Wiki's example and mine works fine. Colors seem to be *alittle* off but not a big deal. 

https://github.com/iRayanKhan/homebridge-tuya/wiki/Supported-Device-Types

**Comment by SoullessElbows** [comment]
> > Was anyone able to fix this issue? Something happening to me for a White and RGB bulb...
> > `[3/20/2021, 21:54:38] [homebridge-tuya] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.`
> 
> Yes I fixed it, you need to define the characteristic's (parameters) of the bulb in the config. I used the Wiki's example and mine works fine. Colors seem to be _alittle_ off but not a big deal.
> 
> https://github.com/iRayanKhan/homebridge-tuya/wiki/Supported-Device-Types

Added my parameters but still getting no control in HomeKit. It shows the items in HomeKit but I’m unable to control them. I’m also getting the Boolean item in my HOOBS log.

**Comment by rikray02** [comment]
Hi have the same problem with this Globe Bulb:  
https://www.canadiantire.ca/en/pdp/globe-a19-led-dimmable-colour-tunable-white-smart-bulb-0529760p.0529760.html?ds_rl=1283573&ds_rl=1283573&gclid=EAIaIQobChMI3_XhlvyV8AIVhofICh3g7Q1NEAQYASABEgLBRfD_BwE&gclsrc=aw.ds#store=101

This is the message on the Homebridge Console: 
4/23/2021, 11:49:01 PM] [homebridge-mqtt-power-consumption-log-tasmota] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[4/23/2021, 11:49:01 PM] [homebridge-tuya] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[Tuya] Sending test {"1":true}

This is the configuration plugin:
{
            "devices": [
                {
                    "type": "RGBTWLight",
                    "name": "test",
                    "id": "xxxxxxxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxxxxxx",
                    "dpBrightness": 3,
                    "dpColorTemperature": 4
                }
            ],
            "platform": "TuyaLan"
        }

Thanks for your help
Best Regards

**Comment by rikray02** [comment]
This is an other information on the console:
[4/23/2021, 11:57:37 PM] [TuyaLan] Discovered a device that has not been configured yet (075710082cf4328055fe@10.0.1.21).
I don't know what does it means.
