### ISSUE TITLE
 [TuyaDiscovery] UDP from Log continues to occur

### ISSUE THREAD

**Issue by Jeoniiiii** [iRayanKhan/homebridge-tuya#78]
I am using 1 cord wifi dedicated smart plug. (4ea)

It is a tuya based device.

It works fine
But in the log
Only the smart plug is continuously searched for devices.
(Other tuya-based devices fine. don't have a log)

I also put the ip address in config
The log does not stop.

Sorry for my lack of English proficiency.

**Comment by Jeoniiiii** [comment]
[TuyaDiscovery] UDP from 192.168.0.23:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.37:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.26:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.34:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.23:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.37:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.26:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.34:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.23:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.37:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.26:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.34:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.23:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.37:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.26:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.34:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.23:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.37:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.26:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.34:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.23:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.37:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.26:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.34:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.23:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.37:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.26:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.34:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.23:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.37:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.26:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.34:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.23:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.37:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.26:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.34:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.23:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.37:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.26:6667 0x000055aa...0x0000aa55

**Comment by allenlicn** [comment]
i noticed the same issue

**Comment by kylepierce** [comment]
+1

**Comment by mrmaximas** [comment]
same issue with binded by IP outlet
TuyaDiscovery] UDP from 192.168.88.167:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.88.167:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.88.167:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.88.167:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.88.167:6667 0x000055aa...0x0000aa55

**Comment by swampsnake1961** [comment]
I have a few devices I access with Tuya Web as Tuya-Lan will not work with them for some strange reason.  They are only basic wifi sockets and nothing unusual, but the just will not work.  I now have some newer devices and have no way of getting the ID's anymore.

Now my Homebridge logs are filling up in 5-6 days with thousands of [TuyaDiscovery] messages.  I really hope there is a way of stopping these as every week I have to stop Hoimebridge, delete and re-create the log file then restart

**Comment by iRayanKhan** [comment]
Hi there, this is being worked on currently, and is part of the V2.0 beta.

A V2.0 beta 1 release will be published Saturday (hopefully), so it should fix this issue. Oznu thankfully told me to use avoid usage of ```console.log()```, and instead use ```this.log```.

**Comment by vascott1** [comment]
Hi there. Was wondering what the status is of V2.0 beta. Would like to help test :)  This issue is back for me because I added a new device that is not supported I believe. It is the Atomi Smart AC Controller. It is a tuya device but set up in the Atomi app. It  does not show in the regular Tuya listing of devices. My guess is it is connected to a different account.

**Comment by iRayanKhan** [comment]
Hi there, I am working on V2.0 still, and anyone can install it from the branch as they please but do not that since it's a big update, it will take time.

My goal is to have it out within 3 weeks. That includes all public beta testing, etc. I honestly may get it done sooner, it just depends. Sorry for all the delay, but it is worth it!

**Comment by vascott1** [comment]
No problem!! Your work is. Rey much appreciated! Let me know when I can install to help test. Always up for some beta fun!
  

  
  

  
  
>

**Comment by galzil** [comment]
Thanks, your work is very appreciated, I'll try to see if I can install the beta on hoobs

**Comment by Al-Mclean** [comment]
Hi All, some of the information here #117 might also be useful to those still having issues

**Comment by galzil** [comment]
I'm willing to try the beta. But I'm not sure it's possible on Hoobs

**Comment by iRayanKhan** [comment]
The beta is possible to revert, but there will be config.json issues.

As for trying it on Hoobs/Config-Ui-X(+ Image), You can do it on Config-Ui-X(+Image) using the command line feature, not sure if hoops has that.

**Comment by Jeoniiiii** [comment]
In the new version 1.0.5 My Tuya smart plug works, but the status update doesn't work The smart plug is actually turned on, but the home bridge says it's turned off. But it works And the udp log still occurs continuously Thank you very much for working hard on the update

**Comment by iRayanKhan** [comment]
I'm positive I have a fix, but want to make it a config option in the future. Do any of y'all have discord?

**Comment by vascott1** [comment]
Vascott1 on discord for me
  

  
  

  
  
>

**Comment by JustAnotherPU** [comment]
@iRayanKhan 

Hey man, thanks for your amazing work, Yesterday I configured everything for my wifi outlet everything was working once I entered manually the ip for each outlet. but today after waking up every plug is not working anymore.
Having a lot of log such as 
[TuyaDiscovery] UDP from 192.168.1.187:6667 0x000055aa...0x0000aa55

But I dont undestand why discovering since my IP is static and specified in the config.json
Is there something I am missing or you have a fix for this ?

**Comment by Bogdis** [comment]
Hello and thank you for your hard work on this plugin :)
Is there any solution yet for the tuyadiscovery log issue?

**Comment by JustAnotherPU** [comment]
Any news about this log issue ? it's make my homebridge very unresponsive, is the update rolling soon ? @iRayanKhan

**Comment by apollo316** [comment]
Having the same problem here. Constant logs showing up. I just want to turn off TuyaDiscovery, the devices I need are already added.

[TuyaDiscovery] UDP from 192.168.xx.xx7:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.xx.xx5:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.xx.xx7:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.xx.xx7:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.xx.xx5:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.xx.xx7:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.xx.xx5:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.xx.xx7:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.xx.xx7:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.xx.xx5:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.xx.xx7:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.xx.xx7:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.xx.xx5:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.xx.xx7:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.xx.xx5:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.xx.xx7:6666 0x000055aa...0x0000aa55

**Comment by GioCirque** [comment]
FWIW: I've locally edited the JavaScript file that writes these to suppress it until it's resolved. This change gets reverted on updates, but I don't mind SSH into the host and making that edit for now.

**Comment by apollo316** [comment]
> FWIW: I've locally edited the JavaScript file that writes these to suppress it until it's resolved. This change gets reverted on updates, but I don't mind SSH into the host and making that edit for now.

That would be amazing!! Can you share what you changed in the TuyaDiscovery.js file so I may replicate this?

**Comment by GioCirque** [comment]
Sure thing. The change is at [TuyaDiscovery.js line 102](https://github.com/iRayanKhan/homebridge-tuya/blob/master/lib/TuyaDiscovery.js#L102) which is installed to `<homebridge_install_dir>/node_modules/homebridge-tuya/lib` for me using a docker image of Homebridge, and presumably in a similar location for other installations. If you did a global install (`npm ... -g`) then it'll be in the global `node_modules` folder. You can find the global folder using `npm config get prefix`

Change this line:
```javascript {.line-numbers}
101: const len = msg.length;
102: console.log(`[TuyaDiscovery] UDP from ${info.address}:${port} 0x${msg.readUInt32BE(0).toString(16).padStart(8, '0')}...0x${msg.readUInt32BE(len - 4).toString(16).padStart(8, '0')}`);
103: if (len < 16 ||
```

To be this:

```javascript {.line-numbers}
101: const len = msg.length;
102: // Commented to suppress log noise until ... maybe v2?
103: // console.log(`[TuyaDiscovery] UDP from ${info.address}:${port} 0x${msg.readUInt32BE(0).toString(16).padStart(8, '0')}...0x${msg.readUInt32BE(len - 4).toString(16).padStart(8, '0')}`);
104: if (len < 16 ||
```

**Comment by apollo316** [comment]
Thanks so much!! @GioCirque

**Comment by Al-Mclean** [comment]
This is my alternate approach - after 10 UDP messages I issue an emit to shutdown Tuya Discovery

[index.txt](https://github.com/iRayanKhan/homebridge-tuya/files/5484790/index.txt)
[TuyaDiscovery.txt](https://github.com/iRayanKhan/homebridge-tuya/files/5484791/TuyaDiscovery.txt)

**Comment by apollo316** [comment]
Nice! Thanks @Al-Mclean 

Far as I can tell this doesn't break anything. It's like the TuyaDiscovery.js is a rogue process that doesn't shut it self down. Thank you!

**Comment by dkossman** [comment]
I had been using the 1.0.5 version of the Tuya-Homebridge plugin with some Treatlife (Tuya-compatible) smart switches without any issues.  I added some Treatlife smart plugs, and started seeing an infinite number of the UDP messages in the log, as noted above.  Updated to the 1.1.0 version of the plugin, but the issue continued to occur.

I then made the changes to index.js and TuyaDiscovery.js (in the 1.1.0 code) per @Al-Mclean's post above, and this has solved the problem.

@iRayanKhan if you don't have any concerns with the approach,  would it be possible for you to merge these changes into the codebase?  Or do you have a different fix planned?

**Comment by iRayanKhan** [comment]
@dkossman publishing a new beta tonight. If it works, this issue will be fixed in the beta after. trying to get V2 out b4 Christmas.

**Comment by dkossman** [comment]
Thanks- will keep an eye out.  Happy to help test.  Note that with the patch noted above, I still have issues where my Treatlife devices stop responding after power is interrupted. If you need details and logs let me know.

**Comment by biosim500** [comment]
I'm waiting anxious for this beta update! This log issue bugs me a lot!

**Comment by AndrewJ1990** [comment]
I'm pretty keen for this too! How do I install the beta though?

**Comment by jeylites** [comment]
Gave VER.2 B4 a try and got the following error.

I’m back on VER. 1.0


![BFA9CE56-1184-4992-A63C-2E0F0021A895](https://user-images.githubusercontent.com/9190080/102185787-8e90f280-3eec-11eb-8fa7-28b9a24b16c2.png)

**Comment by biosim500** [comment]
> Sure thing. The change is at [TuyaDiscovery.js line 102](https://github.com/iRayanKhan/homebridge-tuya/blob/master/lib/TuyaDiscovery.js#L102) which is installed to `<homebridge_install_dir>/node_modules/homebridge-tuya/lib` for me using a docker image of Homebridge, and presumably in a similar location for other installations. If you did a global install (`npm ... -g`) then it'll be in the global `node_modules` folder. You can find the global folder using `npm config get prefix`
> 
> Change this line:
> 
> ```js
> 101: const len = msg.length;
> 102: console.log(`[TuyaDiscovery] UDP from ${info.address}:${port} 0x${msg.readUInt32BE(0).toString(16).padStart(8, '0')}...0x${msg.readUInt32BE(len - 4).toString(16).padStart(8, '0')}`);
> 103: if (len < 16 ||
> ```
> 
> To be this:
> 
> ```js
> 101: const len = msg.length;
> 102: // Commented to suppress log noise until ... maybe v2?
> 103: // console.log(`[TuyaDiscovery] UDP from ${info.address}:${port} 0x${msg.readUInt32BE(0).toString(16).padStart(8, '0')}...0x${msg.readUInt32BE(len - 4).toString(16).padStart(8, '0')}`);
> 104: if (len < 16 ||
> ```

There's a way to change this line without SSH, like from the terminal? I've already tried using some random software to connect to the Raspberry, but i've got no sucess (i really don't know how to do it)

**Comment by iRayanKhan** [comment]
Try v1.2.0

**Comment by biosim500** [comment]
> Try v1.2.0

Solved!
Many, many thanks!

**Comment by iRayanKhan** [comment]
> > Try v1.2.0
> 
> Solved!
> Many, many thanks!

Sweet! Closing now.

**Comment by iRayanKhan** [comment]
> This is my alternate approach - after 10 UDP messages I issue an emit to shutdown Tuya Discovery
> 
> [index.txt](https://github.com/iRayanKhan/homebridge-tuya/files/5484790/index.txt)
> [TuyaDiscovery.txt](https://github.com/iRayanKhan/homebridge-tuya/files/5484791/TuyaDiscovery.txt)

Also going to implement this in 1.2.1

**Comment by jeylites** [comment]
I’m on VER 1.2 seem ok but only when the bulb loses WiFi connection it doesn’t comes back again, at least not with a reboot. 

Is there a way to fix this? Or maybe there should be an option to do an auto discover when is needed.

**Comment by iRayanKhan** [comment]
I personally would've preferred to keep AutoDiscovery always on so you don't have to restart Homebridge, 

I'm still thinking what the best way to implement this will be.

**Comment by jeylites** [comment]
@iRayanKhan 

can auto discovery be added as a selectable option for now until we think of a solution?

**Comment by iRayanKhan** [comment]
> @iRayanKhan 
> 
> 
> 
> can auto discovery be added as a selectable option for now until we think of a solution? 

This is probably the best option, just a config parameter.

**Comment by jeylites** [comment]
Is Autodiscovery an option now on ver1.3?

**Comment by jeylites** [comment]
The latest ver1.3 seem to be crashing Homebridge plugin occasionally when bulbs go offline or on reachable.
